invoice/urls.py
from django.contrib import admin
from django.urls import path
from .views import InvoiceListView1, createInvoice1, generate_PDF1, view_PDF1,update1,updaterecord1,deleteInvoice1, InvoiceListView1datenegative , InvoiceListView1datepositive
from .views import InvoiceListView2, createInvoice2, generate_PDF2, view_PDF2,deleteInvoice2
from django.conf.urls import include
from .views import export

from django.contrib.auth import views as auth_views #new

app_name = 'invoice'

urlpatterns = [
    path('', InvoiceListView1.as_view(), name="invoice-list"),
    path('invoicefilterdatenegative', InvoiceListView1datenegative.as_view(), name="invoice-list-date-negative"),
    path('invoicefilterdatepositive', InvoiceListView1datepositive.as_view(), name="invoice-list-date-positive"),
    path('invoicelist', InvoiceListView2.as_view(), name="invoice-list-2"),


    path('create/', createInvoice1, name="invoice-create"),
    path('createnotax/', createInvoice2, name="invoice-create-2"),


    path('invoice-detail/<id>', view_PDF1, name='invoice-detail'),
    path('invoice-detail-notax/<id>', view_PDF2, name='invoice-detail-2'),



    path('invoice-download/<id>', generate_PDF1, name='invoice-download'),
    path('invoice-download-notax/<id>', generate_PDF2, name='invoice-download-2'),

    path('invoice-delete/<id>', deleteInvoice1, name='invoice-delete'),
    path('invoice-delete-notax/<id>', deleteInvoice2, name='invoice-delete-2'),

    path('update/<int:id>', update1, name='update'),


    path('update/updaterecord/<int:id>', updaterecord1, name='updaterecord'),

  path('export/', export, name='export'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("invoice.urls")),

]

invoice/models.py
from django.db import models
import datetime
# Create your models here.


class Invoice1(models.Model):
    customer = models.CharField(max_length=100)
    bill_title = models.CharField(max_length=100)
    termsandconditions = models.CharField(max_length=100)
    fulldescription = models.CharField(max_length=100)
    date = models.DateField()
    service_type = models.CharField(max_length=100)
    total_amount = models.DecimalField(max_digits=100, decimal_places=2, blank=True, null=True)
    service = models.TextField(max_length=100)
    gst = models.CharField(max_length=100)
    gsttotal = models.CharField(max_length=100)
    subtotal = models.CharField(max_length=100)
    gstpercentage = models.CharField(max_length=100)
    status = models.BooleanField(default=False)
    currency = models.TextField(max_length=100)
    footer = models.TextField(max_length=100)



    def __str__(self):
        return str(self.customer)
    
    def get_status(self):
        return self.status

    # def save(self, *args, **kwargs):
        # if not self.id:             
        #     self.due_date = datetime.datetime.now()+ datetime.timedelta(days=15)
        # return super(Invoice, self).save(*args, **kwargs)

class Invoice2(models.Model):
    customer = models.CharField(max_length=100)
    bill_title = models.CharField(max_length=100)
    termsandconditions = models.CharField(max_length=100)
    fulldescription = models.CharField(max_length=100)
    date = models.DateField()
    service_type = models.CharField(max_length=100)
    total_amount = models.DecimalField(max_digits=100, decimal_places=2, blank=True, null=True)
    service = models.TextField(max_length=100)
    subtotal = models.CharField(max_length=100)
    status = models.BooleanField(default=False)
    currency = models.TextField(max_length=100)
    footer = models.TextField(max_length=100)



    def __str__(self):
        return str(self.customer)

    def get_status(self):
        return self.status

    # def save(self, *args, **kwargs):
        # if not self.id:
        #     self.due_date = datetime.datetime.now()+ datetime.timedelta(days=15)
        # return super(Invoice, self).save(*args, **kwargs)
class LineItem1(models.Model):
    customer = models.ForeignKey(Invoice1, on_delete=models.CASCADE)
    service = models.TextField()
    description = models.TextField()
    quantity = models.IntegerField()
    rate = models.DecimalField(max_digits=100, decimal_places=2)
    amount = models.DecimalField(max_digits=100, decimal_places=2)

    def __str__(self):
        return str(self.customer)

class LineItem2(models.Model):
    customer = models.ForeignKey(Invoice2, on_delete=models.CASCADE)
    service = models.TextField()
    description = models.TextField()
    quantity = models.IntegerField()
    amount = models.CharField(max_length=100)

    def __str__(self):
        return str(self.customer)

invoice/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.template.loader import get_template
from django.http import HttpResponse

from django.contrib.auth import login
from django.contrib import messages
from django.views import View
from .models import LineItem1, Invoice1, LineItem2, Invoice2
from .forms import LineItemFormset1, InvoiceForm1, LineItemFormset2, InvoiceForm2
from django.template import loader
from django.contrib.auth.decorators import login_required

import pdfkit
import csv

class InvoiceListView2(View):

    def get(self, *args, **kwargs):
        invoices2 = Invoice2.objects.all().order_by('-id')
        context = {

            "invoices2": invoices2,
        }

        return render(self.request, 'invoice/invoice-list-2.html', context)


    def post(self, request):
        # import pdb;pdb.set_trace()
        invoice2_ids = request.POST.getlist("invoice2_id")
        invoice2_ids = list(map(int, invoice2_ids))

        invoices2 = Invoice2.objects.filter(id__in=invoice2_ids)
        # import pdb;pdb.set_trace()

        return redirect('invoice:invoice-list-2')


class InvoiceListView1(View):
    def get(self, *args, **kwargs):
        invoices1 = Invoice1.objects.all().order_by('-id')
        context = {
            "invoices1": invoices1,
        }

        return render(self.request, 'invoice/invoice-list.html', context)

    def post(self, request):
        # import pdb;pdb.set_trace()
        invoice1_ids = request.POST.getlist("invoice2_id")
        invoice1_ids = list(map(int, invoice1_ids))

        invoices1 = Invoice1.objects.filter(id__in=invoice1_ids)
        # import pdb;pdb.set_trace()

        return redirect('invoice:invoice-list')



class InvoiceListView1datenegative(View):
    def get(self, *args, **kwargs):
        invoices1 = Invoice1.objects.all().order_by('-date')
        context = {
            "invoices1": invoices1,
        }

        return render(self.request, 'invoice/invoice-list-date-negative.html', context)

    def post(self, request):
        # import pdb;pdb.set_trace()
        invoice1_ids = request.POST.getlist("invoice2_id")
        invoice1_ids = list(map(int, invoice1_ids))

        invoices1 = Invoice1.objects.filter(id__in=invoice1_ids)
        # import pdb;pdb.set_trace()

        return redirect('invoice:invoice-list-date-negative')


class InvoiceListView1datepositive(View):
    def get(self, *args, **kwargs):
        invoices1 = Invoice1.objects.all().order_by('date')
        context = {
            "invoices1": invoices1,
        }

        return render(self.request, 'invoice/invoice-list-date-positive.html', context)

    def post(self, request):
        # import pdb;pdb.set_trace()
        invoice1_ids = request.POST.getlist("invoice2_id")
        invoice1_ids = list(map(int, invoice1_ids))

        invoices1 = Invoice1.objects.filter(id__in=invoice1_ids)
        # import pdb;pdb.set_trace()

        return redirect('invoice:invoice-list-date-positive')



@login_required(login_url='/admin/login/?next=/admin/')
def createInvoice1(request):
    """
    Invoice Generator page it will have Functionality to create new invoices, 
    this will be protected view, only admin has the authority to read and make
    changes here.
    """

    heading_message = 'Apro IT Solutions'
    if request.method == 'GET':
        formset = LineItemFormset1(request.GET or None)
        form = InvoiceForm1(request.GET or None)
    elif request.method == 'POST':
        formset = LineItemFormset1(request.POST)
        form = InvoiceForm1(request.POST)

        gstpercentageinfloat = form.data["gst"]
        a = float(gstpercentageinfloat) * 100
        b = int(a)
        servicea = form.data["service"]
        


        if servicea == 'http://apropack.com/assets/apro-rigs.svg':
            terms1 = form.data["termsandconditionsaprorigs"]
            additionalnotes = form.data["fulldescriptionrigs"]

        elif servicea == 'http://apropack.com/assets/apro-it.svg':
            terms1 = form.data["termsandconditionsaproitsolutions"]
            additionalnotes = form.data["fulldescriptionit"]

        elif servicea == 'http://apropack.com/assets/apro-hosting.svg':
            terms1 = form.data["termsandconditionsaprohosting"]
            additionalnotes = form.data["fulldescriptionaprohosting"]

        else:
            terms1 = form.data["termsandconditionsaprocms"]
            additionalnotes = form.data["fulldescriptioncms"]


        currencycountry = form.data["currency"]
        footerdefault = form.data["footer"]

        if form.is_valid():
            invoice1 = Invoice1.objects.create(customer=form.data["customer"],
                                               bill_title=form.data["bill_title"],
                                               gst=gstpercentageinfloat,
                                               termsandconditions=terms1,
                                               fulldescription=additionalnotes,
                                               date=form.data["date"],
                                               service_type=form.data["service_type"],
                                               gstpercentage=b,
                                               service=servicea,
                                               currency=currencycountry,
                                               footer=footerdefault

                                               )

            # invoice.save()

        if formset.is_valid():
            # import pdb;pdb.set_trace()
            # extract name and other data from each form and save
            total = 0

            for form in formset:
                service = form.cleaned_data.get('service')
                description = form.cleaned_data.get('description')
                quantity = form.cleaned_data.get('quantity')
                rate = form.cleaned_data.get('rate')

                if service and description and quantity and rate:
                    amount = float(rate) * float(quantity)

                    total += amount
                    LineItem1(customer=invoice1,
                              service=service,
                              description=description,
                              quantity=quantity,
                              rate=rate,
                              amount=amount).save()
            invoice1.total_amount = total
            totala = float(total)
            gsta = float(gstpercentageinfloat)
            gsttotala = totala * gsta
            floata = gsttotala
            format_float = "{:.2f}".format(floata)

            invoice1.gsttotal = format_float
            subtotal = gsttotala + totala
            abc = float(subtotal)
            invoice1.subtotal = abc
            invoice1.save()

            try:
                generate_PDF1(request, id=invoice1.id)
            except Exception as e:
                print(f"********{e}********")
            return redirect('/')
    context = {
        "title": "Invoice Generator",
        "formset": formset,
        "form": form,
    }
    return render(request, 'invoice/invoice-create.html', context)

def createInvoice2(request):
    """
    Invoice Generator page it will have Functionality to create new invoices,
    this will be protected view, only admin has the authority to read and make
    changes here.
    """

    heading_message = 'Apro IT Solutions'
    if request.method == 'GET':
        formset = LineItemFormset2(request.GET or None)
        form = InvoiceForm2(request.GET or None)
    elif request.method == 'POST':
        formset = LineItemFormset2(request.POST)
        form = InvoiceForm2(request.POST)

        gstpercentageinfloat = form.data["gst"]
        a = float(gstpercentageinfloat) * 100
        b = int(a)

        servicea = form.data["service"]



        if servicea == 'https://www.aprorigs.com/wp-content/uploads/2021/11/logo3.png':
            terms1 = form.data["termsandconditionsaprorigs"]
            additionalnotes = form.data["fulldescriptionrigs"]

        elif servicea == 'https://aproitsolutions.com/wp-content/uploads/2019/07/apro-logo-for-web-new-dark-1.png':
            terms1 = form.data["termsandconditionsaproitsolutions"]
            additionalnotes = form.data["fulldescriptionit"]

        elif servicea == 'https://aprohosting.com/wp-content/uploads/2021/11/logo-02.png':
            terms1 = form.data["termsandconditionsaprohosting"]
            additionalnotes = form.data["fulldescriptionaprohosting"]

        else:
            terms1 = form.data["termsandconditionsaprocms"]
            additionalnotes = form.data["fulldescriptioncms"]


        currencycountry = form.data["currency"]
        footerdefault = form.data["footer"]

        if form.is_valid():
            invoice2 = Invoice2.objects.create(customer=form.data["customer"],
                                               bill_title=form.data["bill_title"],
                                               gst=gstpercentageinfloat,
                                               termsandconditions=terms1,
                                               fulldescription=additionalnotes,
                                               date=form.data["date"],
                                               service_type=form.data["service_type"],
                                               gstpercentage=b,
                                               service=servicea,
                                               currency=currencycountry,
                                               footer=footerdefault

                                               )

            # invoice.save()

        if formset.is_valid():
            # import pdb;pdb.set_trace()
            # extract name and other data from each form and save
            total = 0

            for form in formset:
                service = form.cleaned_data.get('service')

invoice/templates/invoice/abd.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load humanize %}
    <style>
        	table {
			width:100%;
			height:100%;
			border:1px;
			border-collapse:collapse;
			padding:4px;
		}
		table th {
			border:1px;
			padding:15px;
			background: #f0f0f0;
			color: #313030;
		}
		table td {
			border:1px;
			text-align:left;
			padding:4px;
			color: #313030;
			vertical-align:baseline;
		}
    </style>
</head>
<body>


            <table>
		<thead>
			<tr>
				<th>#</th>
				<th style="padding:10px">Description</th>
				<th>Qty</th>
				<th>Rate</th>
			</tr>
		</thead>
		<tbody>
  {% for item in lineitem %}
			<tr>
				<td style="text-align:center;">{{forloop.counter}}</td>
                <td><div><strong>{{item.service}}</strong></div> <br/><div style="    margin-top: -30px;">{{item.description|linebreaks}}</div></td>
				<td>{{item.quantity}}</td>
				<td>₹ {{item.rate|intcomma}}</td>
			</tr>
  {% endfor %}
		</tbody>

	</table>



</body>
</html>

invoice/templates/invoice/header.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
</head>
<style>
    .header{
        min-height:100px;
        background-color:#0c1a2d;
        color:#fff;
        text-align:center;
    }

</style>
<body>
    <div class="header">
        Hi This is my header template.
    </div>



</body>
</html>

invoice/templates/invoice/invoice-list-2.html
{% extends 'invoice/base.html' %}
{% load static %}
{% block content %}
<div class="columns is-centered has-text-centered">
    <div class="column is-half">
        <div class="card has-background-white-ter">
            <h1 class="title is-3"></h1>
        </div>
    </div>



</div>
<style>
    img {
        display: block;
        margin-left: auto;
        margin-right: auto;
    }
</style>

<script type="text/javascript">
/*
   Willmaster Table Sort
   Version 1.1
   August 17, 2016
   Updated GetDateSortingKey() to correctly sort two-digit months and days numbers with leading 0.
   Version 1.0, July 3, 2011

   Will Bontrager
   https://www.willmaster.com/
   Copyright 2011,2016 Will Bontrager Software, LLC

   This software is provided "AS IS," without
   any warranty of any kind, without even any
   implied warranty such as merchantability
   or fitness for a particular purpose.
   Will Bontrager Software, LLC grants
   you a royalty free license to use or
   modify this software provided this
   notice appears on all copies.
*/
//
// One placed to customize - The id value of the table tag.

var TableIDvalue = "indextable";

//
//////////////////////////////////////
var TableLastSortedColumn = -1;
function SortTable() {
var sortColumn = parseInt(arguments[0]);
var type = arguments.length > 1 ? arguments[1] : 'T';
var dateformat = arguments.length > 2 ? arguments[2] : '';
var table = document.getElementById(TableIDvalue);
var tbody = table.getElementsByTagName("tbody")[0];
var rows = tbody.getElementsByTagName("tr");
var arrayOfRows = new Array();
type = type.toUpperCase();
dateformat = dateformat.toLowerCase();
for(var i=0, len=rows.length; i<len; i++) {
	arrayOfRows[i] = new Object;
	arrayOfRows[i].oldIndex = i;
	var celltext = rows[i].getElementsByTagName("td")[sortColumn].innerHTML.replace(/<[^>]*>/g,"");
	if( type=='D' ) { arrayOfRows[i].value = GetDateSortingKey(dateformat,celltext); }
	else {
		var re = type=="N" ? /[^\.\-\+\d]/g : /[^a-zA-Z0-9]/g;
		arrayOfRows[i].value = celltext.replace(re,"").substr(0,25).toLowerCase();
		}
	}
if (sortColumn == TableLastSortedColumn) { arrayOfRows.reverse(); }
else {
	TableLastSortedColumn = sortColumn;
	switch(type) {
		case "N" : arrayOfRows.sort(CompareRowOfNumbers); break;
		case "D" : arrayOfRows.sort(CompareRowOfNumbers); break;
		default  : arrayOfRows.sort(CompareRowOfText);
		}
	}
var newTableBody = document.createElement("tbody");
for(var i=0, len=arrayOfRows.length; i<len; i++) {
	newTableBody.appendChild(rows[arrayOfRows[i].oldIndex].cloneNode(true));
	}
table.replaceChild(newTableBody,tbody);
} // function SortTable()

function CompareRowOfText(a,b) {
var aval = a.value;
var bval = b.value;
return( aval == bval ? 0 : (aval > bval ? 1 : -1) );
} // function CompareRowOfText()

function CompareRowOfNumbers(a,b) {
var aval = /\d/.test(a.value) ? parseFloat(a.value) : 0;
var bval = /\d/.test(b.value) ? parseFloat(b.value) : 0;
return( aval == bval ? 0 : (aval > bval ? 1 : -1) );
} // function CompareRowOfNumbers()

function GetDateSortingKey(format,text) {
if( format.length < 1 ) { return ""; }
format = format.toLowerCase();
text = text.toLowerCase();
text = text.replace(/^[^a-z0-9]*/,"");
text = text.replace(/[^a-z0-9]*$/,"");
if( text.length < 1 ) { return ""; }
text = text.replace(/[^a-z0-9]+/g,",");
var date = text.split(",");
if( date.length < 3 ) { return ""; }
var d=0, m=0, y=0;
for( var i=0; i<3; i++ ) {
	var ts = format.substr(i,1);
	if( ts == "d" ) { d = date[i]; }
	else if( ts == "m" ) { m = date[i]; }
	else if( ts == "y" ) { y = date[i]; }
	}
d = d.replace(/^0/,"");
if( d < 10 ) { d = "0" + d; }
if( /[a-z]/.test(m) ) {
	m = m.substr(0,3);
	switch(m) {
		case "jan" : m = String(1); break;
		case "feb" : m = String(2); break;
		case "mar" : m = String(3); break;
		case "apr" : m = String(4); break;
		case "may" : m = String(5); break;
		case "jun" : m = String(6); break;
		case "jul" : m = String(7); break;
		case "aug" : m = String(8); break;
		case "sep" : m = String(9); break;
		case "oct" : m = String(10); break;
		case "nov" : m = String(11); break;
		case "dec" : m = String(12); break;
		default    : m = String(0);
		}
	}
m = m.replace(/^0/,"");
if( m < 10 ) { m = "0" + m; }
y = parseInt(y);
if( y < 100 ) { y = parseInt(y) + 2000; }
return "" + String(y) + "" + String(m) + "" + String(d) + "";
} // function GetDateSortingKey()
</script>




<object data="{% static 'img/logo%20new.svg' %}" width="300" height="auto"> </object>





<form action="{% url 'invoice:invoice-list-2' %}" method="post">
    {% csrf_token %}


    <div class="card">
        <header class="card-header">
            <p class="card-header-title">
                All Orders (Non Taxed)&nbsp;
                <div><button class="button is-rounded is-info">
                <a href="{% url 'invoice:invoice-create' %}" class="has-text-white">Create New Tax Based Estimate</a>
                </button></div>
             <div><button class="button is-rounded is-info">
                <a href="{% url 'invoice:invoice-create-2' %}" class="has-text-white">Create New Non Tax Based Estimate</a>
                </button></div>
            <div><button class="button is-rounded is-info">
                <a href="{% url 'invoice:invoice-list' %}" class="has-text-white">View Tax Based Estimate</a>
                </button></div>
            <div><button class="button is-rounded is-info">
                <a href="{% url 'invoice:invoice-list-2' %}" class="has-text-white">View Non Tax Based Estimate</a>
                </button></div>


            </p>

        </header>
        <div class="card-content">
            <div class="content">

                <table class="table is-fullwidth is-bordered is-hoverable is-striped" id="myTable">
                    <tbody>
                    <thead>
                        <tr>
                            <!--<th></th>-->
                            <th data-tablesort="number" style="cursor: cell;">SI. No.</th>
                            <th >CUSTOMER</th>
                            <th>SERVICE TYPE</th>
                            <th>DATE</th>


                            <th>TOTAL</th>

                            <th>View</th>

                            <th>Delete</th>
                            <th>Download</th>


                        </tr>
                    </thead>
                    {% for invoice2 in invoices2 %}
                    <tr>

                        <td width="10%">{{invoice2.id}}</td>
                        <td width="39%">{{invoice2.customer}}</td>
                        <td width="39%">{{invoice2.service_type}}</td>
                        <td width="39%"> {{invoice2.date}}</td>


                        <td>{{invoice2.total_amount}}</td>
                        <!--<td class="level-right">
                            {% if invoice.get_status %}
                            <a class="button is-small is-success" href="#">Paid</a>
                            {% else %}
                            <a class="button is-small is-warning" href="#">Not Paid</a>
                            {% endif %}
                        </td>-->
                           <td width="1%">
                            <a href="{% url 'invoice:invoice-detail-2' id=invoice2.id %}">
                                <div class="button is-small is-info">View</div>
                            </a>
                        </td>

                         <td width="1%">
                            <a href="{% url 'invoice:invoice-delete-2' id=invoice2.id %}">

                                <div style="font-weight: bold;
color: red;">Delete</div>
                            </a>


                        </td>



                        <td width="1%">
                            <a href="{% url 'invoice:invoice-download-2' id=invoice2.id %}">
                                <div class="button is-small is-info">Download</div>
                            </a>
                        </td>
                    </tr>
                    {% endfor %}

                    </tbody>
                </table>

            </div>
        </div>
    </div><br /><br /><br />
    <!--<div class="card has-background-white-ter">
        <header class="card-header">
            <p class="card-header-title">
                Change Order Status
            </p>
        </header>
        <div class="card-content">
            <div class="select is-rounded">
                <select id="status" name="status">
                    <option value="1">Paid</option>
                    <option value="0">Not Paid</option>
                </select>
            </div>
            <input class="button  is-info is-rounded" type="submit" class="btn" value="Change Status" name="mybtn">
        </div>
    </div>-->
</form>

{% endblock content %}

invoice/templates/invoice/newpdf.html
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>CodePen - flexbox table</title>
<style>
    .Tablea {
  display : flex;
  flex-direction : row;
   border: 1px solid #f2f2f2;
  font-size: 1rem;
  margin: 0.5rem;
  line-height: 1.5;
  justify-content : space-between;
}

.Tablea-header {
  font-weight: 700;
    background-color: #defdec;
}

  .Tablea-row {
    display: -webkit-box;
    display: -moz-box;
    display: box;
    display: -webkit-flex;
    display: -moz-flex;
    display: -ms-flexbox;
    display: flex;
    -webkit-flex-flow: row nowrap;
    -moz-flex-flow: row nowrap;
    flex-flow: row nowrap;
  }
  .Tablea-row:nth-of-type(even) {
    background-color: #ffffff;
  }
  .Tablea-row:nth-of-type(odd) {
    background-color: #f2f2f2;
  }

.Tablea-row-item {
  display : flex;
  flex-grow :1;
    padding: 0.5em;
  /* border: 1px solid #fff; */
  word-break: break-word;
}


.u-Flex-grow1 {
  -webkit-flex-grow: 1;
  -moz-flex-grow: 1;
  flex-grow: 0.5;
  -ms-flex-positive: 1;
}

.u-Flex-grow2 {
  -webkit-flex-grow: 2;
  -moz-flex-grow: 2;
  flex-grow: 2.1;
  -ms-flex-positive: 2;
}

.u-Flex-grow3 {
  -webkit-flex-grow: 3;
  -moz-flex-grow: 3;
  flex-grow: 3;
  -ms-flex-positive: 3;
}

.u-Flex-grow4 {
  -webkit-flex-grow: 4;
  -moz-flex-grow: 4;
  flex-grow: 4;
  -ms-flex-positive: 4;
}

.u-Flex-grow5 {
  -webkit-flex-grow: 5;
  -moz-flex-grow: 5;
  flex-grow: 5;
  -ms-flex-positive: 5;
}

.u-Flex-grow6 {
  -webkit-flex-grow: 6;
  -moz-flex-grow: 6;
  flex-grow: 6;
  -ms-flex-positive: 6;
}

.u-Flex-grow7 {
  -webkit-flex-grow: 7;
  -moz-flex-grow: 7;
  flex-grow: 7;
  -ms-flex-positive: 7;
}

.u-Flex-grow8 {
  -webkit-flex-grow: 8;
  -moz-flex-grow: 8;
  flex-grow: 8;
  -ms-flex-positive: 8;
}

.u-Flex-grow9 {
  -webkit-flex-grow: 9;
  -moz-flex-grow: 9;
  flex-grow: 9;
  -ms-flex-positive: 9;
}

.u-Flex-grow10 {
  -webkit-flex-grow: 10;
  -moz-flex-grow: 10;
  flex-grow: 10;
  -ms-flex-positive: 10;
}
</style>

</head>
<body>
<!-- partial:index.partial.html -->
<div class="Tablea">
  <div class="Tablea-row Table-header">
    <div class="Tablea-row-item u-Flex-grow2">#</div>
    <div class="Tablea-row-item">Description</div>
    <div class="Tablea-row-item">Qty</div>
    <div class="Tablea-row-item">Rate</div>

  </div>
  <div class="Tablea-row">
       {% for item in lineitem %}
    <div class="Tablea-row-item u-Flex-grow2" data-header="Header1">{{forloop.counter}}</div>
    <div class="Tablea-row-item" data-header="Header2">{{item.service}}</div>
    <div class="Tablea-row-item" data-header="Header3">{{item.quantity}}</div>
    <div class="Tablea-row-item" data-header="Header4">{{item.rate}}</div>
      {% endfor %}

  </div>


  <div class="Tablea-row">
    <div class="Tablea-row-item u-Flex-grow2" data-header="Header1">row4 col1</div>
    <div class="Tablea-row-item" data-header="Header2">row4 col2</div>
    <div class="Tablea-row-item" data-header="Header3">row4 col3</div>
    <div class="Tablea-row-item" data-header="Header4">row4 col4</div>

  </div>
</div>
<!-- partial -->

</body>
</html>

invoice/templates/invoice/search_results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Search Results</h1>

<ul>
  {% for city in object_list %}
    <li>
      {{ city.name }}, {{ city.state }}
    </li>
  {% endfor %}
</ul>
</body>
</html>

invoice/templates/invoice/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div style="text-align: center;">
    <object data="/static/img/logo%2520new.svg" width="12%" height="auto"> </object>
    <h1 style="text-align:center;">Update Panel</h1>
</div>
<h1>Customer ID {{invoice1.id}}</h1>

<form action="updaterecord/{{ invoice1.id }}" method="post">
{% csrf_token %}
Customer Name:<br>
<input name="customername" value="{{ invoice1.customer }}">
<br><br>
Bill Title:<br>
<input name="billtitle" value="{{ invoice1.bill_title }}">
<br><br>
Service Type:<br>
<input name="service_type" value="{{ invoice1.service_type }}">
<br><br>



<input type="submit" value="Submit">
</form>
</body>
</html>